package com.cloudwalk.ipsim.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "transactions")
@Getter
@Setter
@NoArgsConstructor
public class Transaction {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(nullable = false)
    private BigDecimal amount;

    @Column
    private BigDecimal netAmount; // Amount after fees

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TransactionType type;

    @Column(nullable = false)
    private int installments; // 1 for debit/credit-spot

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TransactionStatus status;

    @Column(nullable = false)
    private LocalDateTime timestamp;

    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "card_id", nullable = false)
    private Card card;

    // =====================================================
    // InfinitePay Integration Fields (NEW)
    // =====================================================

    /**
     * Your internal order identifier
     *
     * Format: ORD-{timestamp}-{uuid}
     * Example: ORD-1708234567-a1b2c3
     *
     * Used to:
     * - Track payments across systems
     * - Match webhooks to transactions
     * - Reconcile with your internal systems
     */
    @Column(unique = true, length = 50)
    private String orderNsu;

    /**
     * InfinitePay checkout URL
     *
     * The payment link that was generated by InfinitePay
     * User opens this URL in browser to complete payment
     *
     * Example: https://pay.infinitepay.io/c/abc123def456
     */
    @Column(length = 500)
    private String checkoutUrl;

    /**
     * InfinitePay invoice slug/identifier
     *
     * Returned when creating checkout link
     * Used for status checks and tracking
     */
    @Column(length = 100)
    private String infinitePaySlug;

    /**
     * InfinitePay transaction NSU (UUID)
     *
     * Unique identifier from InfinitePay for the completed payment
     * Received via webhook when payment succeeds
     */
    @Column(length = 100)
    private String infinitePayTransactionNsu;

    /**
     * URL to payment receipt/proof
     *
     * Provided by InfinitePay via webhook
     * Can be shown to user or stored for records
     *
     * Example: https://comprovante.infinitepay.io/123
     */
    @Column(length = 500)
    private String receiptUrl;
}
